#!/usr/bin/env bash
#while_best_school: prints Best School 10 times

count=0

while [[ "$count" -lt 10 ]]; do
      echo "Best School"
      count=$((count + 1))
      if [[ "$count" -eq 9 ]]; then
	  echo "Hi"
	 fi
done
